PointageZones/Models/Observation.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace PointageZones.Models
{
    public class Observation
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [StringLength(255)]
        public required string Description { get; set; }

        // Navigation property for PointageAgents with this observation
        public ICollection<PointageAgent>? PointageAgents { get; set; }
    }
}

PointageZones/Controllers/ObservationsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PointageZones.Data;
using PointageZones.Models;

namespace PointageZones.Controllers
{
    public class ObservationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ObservationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ObservationsController
        public async Task<ActionResult> IndexAsync()
        {
            return View(await _context.Observations.ToListAsync());
        }

        // GET: ObservationsController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ObservationsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Id,Description")] Observation observation)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    observation.Description = observation.Description.Trim();
                    _context.Add(observation);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(observation); // Ensure a return value for invalid ModelState
            }
            catch
            {
                return View(observation); // Ensure a return value in case of exception
            }
        }

        // GET: Observations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Observation = await _context.Observations.FindAsync(id);
            if (Observation == null)
            {
                return NotFound();
            }
            return View(Observation);
        }

        // POST: observations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description")] Observation observation)
        {
            if (id != observation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(observation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ObservationExists(observation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["Notification"] = "Zone Mis a jour avec succés";
                return RedirectToAction(nameof(Index));
            }
            return View(observation);
        }

        // GET: observations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var observation = await _context.Observations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (observation == null)
            {
                return NotFound();
            }

            return View(observation);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var observation = await _context.Observations.FindAsync(id);
            if (observation != null)
            {
                _context.Observations.Remove(observation); // Corrected DbSet to Observations
            }

            await _context.SaveChangesAsync();
            TempData["Notification"] = "Observation supprimée avec succès";
            return RedirectToAction(nameof(Index));
        }

        private bool ObservationExists(int id)
        {
            return _context.Observations.Any(e => e.Id == id);
        }
    }
}

PointageZones/Views/Observations/Create.cshtml
@model PointageZones.Models.Observation

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Observation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Observations" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Observations" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

PointageZones/Views/Observations/Edit.cshtml
@model PointageZones.Models.Observation

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>Observation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

PointageZones/Views/Observations/Index.cshtml
@model IEnumerable<PointageZones.Models.Observation>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />

<p>
    <a asp-action="Create" class="btn btn-success">Créer Une Nouvelle Observation</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Description)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                
                <td>
                    <div class="d-flex flex-column flex-md-row gap-2">
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning text-uppercase">Modifier</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger text-uppercase">Supprimer</a>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>